import { addDays, todayISO } from './dates'
import type { AppState, Assessor, Participant, Project } from './types'

export const DEMO_CDP = { name: 'Camille Laurent', title: 'Cheffe de projet' }

const assessors: Assessor[] = [
  { id: 'a-sophie', name: 'Sophie Durand', title: 'Associée · Lead assesseure', email: 'sophie.durand@authentictalent.fr' },
  { id: 'a-thomas', name: 'Thomas Bernard', title: 'Consultant senior', email: 'thomas.bernard@authentictalent.fr' },
  { id: 'a-nadia', name: 'Nadia Benali', title: 'Associée · Lead assesseure', email: 'nadia.benali@authentictalent.fr' },
  { id: 'a-julien', name: 'Julien Morel', title: 'Consultant', email: 'julien.morel@authentictalent.fr' },
  { id: 'a-ines', name: 'Inès Garnier', title: 'Consultante senior', email: 'ines.garnier@authentictalent.fr' },
]

const blank = {
  preAnswers: {},
  postAnswers: {},
  postQuestionnaire: 'todo' as const,
  feedback: { status: 'locked' as const },
}

export function buildSeed(): AppState {
  const today = todayISO()

  const projects: Project[] = [
    {
      id: 'pr-sanofi',
      purpose: 'AC',
      format: 'robuste',
      client: 'Sanofi',
      position: 'Directeur·rice des Opérations industrielles',
      sponsorName: 'Marc Lefèvre',
      sponsorTitle: 'DRH Affaires industrielles',
      date: today,
      startTime: '09:00',
      location: 'Distanciel · Microsoft Teams',
      teamsUrl: 'https://teams.microsoft.com/l/meetup-join/atc-sanofi',
      exercises: [
        { id: 'ex-s1', catalogId: 'entretien', duration: 60, assessorId: 'a-sophie' },
        { id: 'ex-s2', catalogId: 'etude-cas', duration: 75, assessorId: 'a-thomas' },
        { id: 'ex-s3', catalogId: 'jeu-role', duration: 30, assessorId: 'a-sophie' },
      ],
      competencyIds: ['vision', 'leadership', 'resultats', 'influence', 'decision'],
      leadAssessorId: 'a-sophie',
      secondAssessorIds: ['a-thomas'],
      debriefClientDone: false,
    },
    {
      id: 'pr-orange',
      purpose: 'DC',
      format: 'premium',
      client: 'Orange',
      position: 'Programme Leaders de demain',
      sponsorName: 'Hélène Roussel',
      sponsorTitle: 'Directrice Talents & Développement',
      date: addDays(today, 12),
      startTime: '08:45',
      location: 'Paris · Siège Orange',
      teamsUrl: 'https://teams.microsoft.com/l/meetup-join/atc-orange',
      exercises: [
        { id: 'ex-o1', catalogId: 'entretien', duration: 60, assessorId: 'a-nadia' },
        { id: 'ex-o2', catalogId: 'in-basket', duration: 45, assessorId: 'a-sophie' },
        { id: 'ex-o3', catalogId: 'etude-cas', duration: 75, assessorId: 'a-julien' },
        { id: 'ex-o4', catalogId: 'pause', duration: 60, assessorId: null },
        { id: 'ex-o5', catalogId: 'jeu-role', duration: 30, assessorId: 'a-sophie' },
        { id: 'ex-o6', catalogId: 'presentation', duration: 30, assessorId: 'a-nadia' },
        { id: 'ex-o7', catalogId: 'groupe', duration: 45, assessorId: null },
      ],
      competencyIds: ['vision', 'leadership', 'influence', 'agilite', 'decision'],
      leadAssessorId: 'a-nadia',
      secondAssessorIds: ['a-sophie', 'a-julien'],
      debriefClientDone: false,
    },
    {
      id: 'pr-safran',
      purpose: 'AC',
      format: 'light',
      client: 'Safran',
      position: 'Responsable Achats Europe',
      sponsorName: 'Olivier Marchand',
      sponsorTitle: 'Directeur Achats Groupe',
      date: addDays(today, 5),
      startTime: '14:00',
      location: 'Distanciel · Microsoft Teams',
      teamsUrl: 'https://teams.microsoft.com/l/meetup-join/atc-safran',
      exercises: [{ id: 'ex-f1', catalogId: 'entretien', duration: 90, assessorId: null }],
      competencyIds: ['resultats', 'influence', 'decision'],
      leadAssessorId: null,
      secondAssessorIds: [],
      debriefClientDone: false,
    },
    {
      id: 'pr-hermes',
      purpose: 'AC',
      format: 'robuste',
      client: 'Hermès',
      position: 'Directeur·rice Retail France',
      sponsorName: 'Claire Vasseur',
      sponsorTitle: 'DRH Retail',
      date: addDays(today, -9),
      startTime: '09:00',
      location: 'Paris · Faubourg Saint-Honoré',
      teamsUrl: 'https://teams.microsoft.com/l/meetup-join/atc-hermes',
      exercises: [
        { id: 'ex-h1', catalogId: 'entretien', duration: 60, assessorId: 'a-ines' },
        { id: 'ex-h2', catalogId: 'presentation', duration: 30, assessorId: 'a-thomas' },
        { id: 'ex-h3', catalogId: 'jeu-role', duration: 30, assessorId: 'a-ines' },
      ],
      competencyIds: ['vision', 'leadership', 'influence', 'agilite'],
      leadAssessorId: 'a-ines',
      secondAssessorIds: ['a-thomas'],
      debriefClientDone: true,
    },
  ]

  const participants: Participant[] = [
    {
      ...blank,
      id: 'pa-jean',
      projectId: 'pr-sanofi',
      firstName: 'Jean',
      lastName: 'Dupont',
      email: 'jean.dupont@exemple.fr',
      currentRole: 'Directeur de site · Le Trait',
      invitedAt: addDays(today, -21),
      hogan: 'done',
      preQuestionnaire: 'done',
      preAnswers: {
        parcours: "Ingénieur de formation, 18 ans dans l'industrie pharmaceutique, dont 6 à la tête d'un site de production de 400 personnes.",
        reussite: 'Le redressement des indicateurs qualité du site en 18 mois, sans plan social.',
        motivation: "Passer d'un site à une vision multi-sites et contribuer à la stratégie industrielle.",
        attentes: 'Un regard extérieur sur mes forces et mes angles morts.',
      },
      dayProgress: -1,
    },
    {
      ...blank,
      id: 'pa-amelie',
      projectId: 'pr-sanofi',
      firstName: 'Amélie',
      lastName: 'Roux',
      email: 'amelie.roux@exemple.fr',
      currentRole: 'Directrice supply chain Europe',
      invitedAt: addDays(today, -21),
      hogan: 'done',
      preQuestionnaire: 'done',
      dayProgress: 1,
    },
    {
      ...blank,
      id: 'pa-karim',
      projectId: 'pr-sanofi',
      firstName: 'Karim',
      lastName: 'Haddad',
      email: 'karim.haddad@exemple.fr',
      currentRole: 'Responsable industrialisation',
      invitedAt: addDays(today, -19),
      hogan: 'done',
      preQuestionnaire: 'todo',
      dayProgress: -1,
    },
    {
      ...blank,
      id: 'pa-leila',
      projectId: 'pr-orange',
      firstName: 'Leïla',
      lastName: 'Mansouri',
      email: 'leila.mansouri@exemple.fr',
      currentRole: 'Head of B2B Marketing',
      invitedAt: addDays(today, -6),
      hogan: 'done',
      preQuestionnaire: 'todo',
      dayProgress: -1,
    },
    {
      ...blank,
      id: 'pa-paul',
      projectId: 'pr-orange',
      firstName: 'Paul',
      lastName: 'Girard',
      email: 'paul.girard@exemple.fr',
      currentRole: 'Directeur des opérations réseau Sud',
      invitedAt: addDays(today, -6),
      hogan: 'todo',
      preQuestionnaire: 'todo',
      dayProgress: -1,
    },
    {
      ...blank,
      id: 'pa-ines',
      projectId: 'pr-orange',
      firstName: 'Inès',
      lastName: 'Faure',
      email: 'ines.faure@exemple.fr',
      currentRole: 'Responsable transformation digitale',
      invitedAt: addDays(today, -6),
      hogan: 'done',
      preQuestionnaire: 'done',
      dayProgress: -1,
    },
    {
      ...blank,
      id: 'pa-hugo',
      projectId: 'pr-orange',
      firstName: 'Hugo',
      lastName: 'Lemaire',
      email: 'hugo.lemaire@exemple.fr',
      currentRole: 'Product Owner senior',
      invitedAt: addDays(today, -6),
      hogan: 'todo',
      preQuestionnaire: 'todo',
      dayProgress: -1,
    },
    {
      ...blank,
      id: 'pa-clara',
      projectId: 'pr-safran',
      firstName: 'Clara',
      lastName: 'Martin',
      email: 'clara.martin@exemple.fr',
      currentRole: 'Acheteuse famille senior',
      invitedAt: addDays(today, -3),
      hogan: 'todo',
      preQuestionnaire: 'todo',
      dayProgress: -1,
    },
    {
      ...blank,
      id: 'pa-lucas',
      projectId: 'pr-hermes',
      firstName: 'Lucas',
      lastName: 'Petit',
      email: 'lucas.petit@exemple.fr',
      currentRole: 'Directeur régional Retail Ouest',
      invitedAt: addDays(today, -35),
      hogan: 'done',
      preQuestionnaire: 'done',
      dayProgress: 3,
      postQuestionnaire: 'done',
      postAnswers: { organisation: '5', exercices: '4', assesseurs: '5', ressenti: 'Exigeant mais bienveillant.' },
      feedback: {
        status: 'unlocked',
        sessionDate: addDays(today, 3),
        sessionTime: '10:00',
        summary:
          "Un leader engagé et fédérateur, qui inspire confiance à ses équipes. Votre capacité à porter une vision claire du client final est un atout marquant. L'enjeu des prochains mois : gagner en recul face à la pression opérationnelle pour déléguer davantage.",
        strengths: [
          'Une vision client incarnée et communicative',
          "Une écoute réelle, qui crée l'engagement",
          'Une grande solidité dans les échanges contradictoires',
        ],
        development: [
          "Déléguer plus tôt les sujets opérationnels pour libérer du temps stratégique",
          'Structurer davantage vos prises de parole devant un comité',
        ],
      },
    },
    {
      ...blank,
      id: 'pa-sarah',
      projectId: 'pr-hermes',
      firstName: 'Sarah',
      lastName: 'Cohen',
      email: 'sarah.cohen@exemple.fr',
      currentRole: 'Directrice de boutique · Paris',
      invitedAt: addDays(today, -35),
      hogan: 'done',
      preQuestionnaire: 'done',
      dayProgress: 3,
      postQuestionnaire: 'done',
      postAnswers: { organisation: '4', exercices: '5', assesseurs: '5', ressenti: 'Très riche.' },
    },
  ]

  return {
    seededOn: today,
    session: null,
    projects,
    participants,
    assessors,
    notes: {
      'pa-sarah:ex-h1:a-ines': {
        text: "Exemples précis et chiffrés. Situation STAR très claire sur la refonte de l'expérience client en boutique.",
        updatedAt: `${addDays(today, -9)}T10:05:00`,
      },
    },
    grid: {
      'pa-sarah:vision': { score: 4, evidence: 'Projette sa boutique à 3 ans avec des jalons concrets.' },
      'pa-sarah:leadership': { score: 5, evidence: 'Jeu de rôle : a recadré avec tact, collaborateur engagé en sortie.' },
    },
    checklist: { 'a-sophie:pa-jean:dossier': true, 'a-sophie:pa-jean:hogan': true },
  }
}

/** Décale toutes les dates de la démo pour qu'elle reste vivante d'un jour à l'autre. */
export function shiftDemo(state: AppState, days: number): AppState {
  if (!days) return state
  return {
    ...state,
    seededOn: addDays(state.seededOn, days),
    projects: state.projects.map((p) => ({ ...p, date: addDays(p.date, days) })),
    participants: state.participants.map((p) => ({
      ...p,
      invitedAt: addDays(p.invitedAt, days),
      feedback: p.feedback.sessionDate ? { ...p.feedback, sessionDate: addDays(p.feedback.sessionDate, days) } : p.feedback,
    })),
  }
}
