import { addDays, businessDay, todayISO } from './dates'
import { teamsLink } from './project'
import type { AppState, Assessor, Participant, Project, Slot, User } from './types'

const users: User[] = [
  { id: 'u-margaux', name: 'Margaux Lefort', email: 'margaux.lefort@authentictalent.fr', role: 'admin', title: 'Directrice des opérations', active: true },
  { id: 'u-camille', name: 'Camille Laurent', email: 'camille.laurent@authentictalent.fr', role: 'cdp', title: 'Cheffe de projet', active: true },
  { id: 'u-julie', name: 'Julie Mercier', email: 'julie.mercier@authentictalent.fr', role: 'cdp', title: 'Cheffe de projet', active: true },
]

const assessors: Assessor[] = [
  { id: 'a-sophie', name: 'Sophie Durand', title: 'Associée · Lead assesseure', email: 'sophie.durand@authentictalent.fr', active: true },
  { id: 'a-thomas', name: 'Thomas Bernard', title: 'Consultant senior', email: 'thomas.bernard@authentictalent.fr', active: true },
  { id: 'a-nadia', name: 'Nadia Benali', title: 'Associée · Lead assesseure', email: 'nadia.benali@authentictalent.fr', active: true },
  { id: 'a-julien', name: 'Julien Morel', title: 'Consultant', email: 'julien.morel@authentictalent.fr', active: true },
  { id: 'a-ines', name: 'Inès Garnier', title: 'Consultante senior', email: 'ines.garnier@authentictalent.fr', active: true },
]

const blank = {
  preAnswers: {},
  postAnswers: {},
  postQuestionnaire: 'todo' as const,
  feedback: { status: 'locked' as const },
  dayProgress: -1,
}

const todo = (): Slot => ({ status: 'todo', proposals: [], counter: [] })
const confirmed = (date: string, time: string): Slot => ({ status: 'confirmed', proposals: [], counter: [], confirmed: { date, time } })

export function buildSeed(): AppState {
  const today = todayISO()
  const d = (n: number) => businessDay(addDays(today, n))

  const projects: Project[] = [
    {
      id: 'pr-sanofi',
      cdpId: 'u-camille',
      purpose: 'AC',
      format: 'robuste',
      client: 'Sanofi',
      position: 'Directeur·rice des Opérations industrielles',
      sponsorName: 'Marc Lefèvre',
      sponsorTitle: 'DRH Affaires industrielles',
      sponsorEmail: 'marc.lefevre@exemple.fr',
      period: 'Octobre 2026',
      startTime: '09:00',
      venue: { mode: 'teams', address: '' },
      exercises: [
        { id: 'ex-s1', catalogId: 'entretien', duration: 60, assessorId: 'a-sophie' },
        { id: 'ex-s2', catalogId: 'etude-cas', duration: 75, assessorId: 'a-thomas' },
        { id: 'ex-s3', catalogId: 'jeu-role', duration: 30, assessorId: 'a-sophie' },
      ],
      competencyIds: ['vision', 'leadership', 'resultats', 'influence', 'decision'],
      leadAssessorId: 'a-sophie',
      secondAssessorIds: ['a-thomas'],
      debriefClientDone: false,
    },
    {
      id: 'pr-orange',
      cdpId: 'u-camille',
      purpose: 'DC',
      format: 'premium',
      client: 'Orange',
      position: 'Programme Leaders de demain',
      sponsorName: 'Hélène Roussel',
      sponsorTitle: 'Directrice Talents & Développement',
      sponsorEmail: 'helene.roussel@exemple.fr',
      period: 'Novembre 2026',
      startTime: '08:45',
      venue: { mode: 'site', address: 'Paris · Siège Orange' },
      exercises: [
        { id: 'ex-o1', catalogId: 'entretien', duration: 60, assessorId: 'a-nadia' },
        { id: 'ex-o2', catalogId: 'in-basket', duration: 45, assessorId: 'a-sophie' },
        { id: 'ex-o3', catalogId: 'etude-cas', duration: 75, assessorId: 'a-julien' },
        { id: 'ex-o4', catalogId: 'pause', duration: 60, assessorId: null },
        { id: 'ex-o5', catalogId: 'jeu-role', duration: 30, assessorId: 'a-sophie' },
        { id: 'ex-o6', catalogId: 'presentation', duration: 30, assessorId: 'a-nadia' },
        { id: 'ex-o7', catalogId: 'groupe', duration: 45, assessorId: null },
      ],
      competencyIds: ['vision', 'leadership', 'influence', 'agilite', 'decision'],
      leadAssessorId: 'a-nadia',
      secondAssessorIds: ['a-sophie', 'a-julien'],
      debriefClientDone: false,
    },
    {
      id: 'pr-safran',
      cdpId: 'u-julie',
      purpose: 'AC',
      format: 'light',
      client: 'Safran',
      position: 'Responsable Achats Europe',
      sponsorName: 'Olivier Marchand',
      sponsorTitle: 'Directeur Achats Groupe',
      sponsorEmail: 'olivier.marchand@exemple.fr',
      period: '',
      startTime: '14:00',
      venue: { mode: 'teams', address: '' },
      exercises: [{ id: 'ex-f1', catalogId: 'entretien', duration: 90, assessorId: null }],
      competencyIds: ['resultats', 'influence', 'decision'],
      leadAssessorId: null,
      secondAssessorIds: [],
      debriefClientDone: false,
    },
    {
      id: 'pr-hermes',
      cdpId: 'u-julie',
      purpose: 'AC',
      format: 'robuste',
      client: 'Hermès',
      position: 'Directeur·rice Retail France',
      sponsorName: 'Claire Vasseur',
      sponsorTitle: 'DRH Retail',
      sponsorEmail: 'claire.vasseur@exemple.fr',
      period: 'Septembre 2026',
      startTime: '09:00',
      venue: { mode: 'site', address: 'Paris · Faubourg Saint-Honoré' },
      exercises: [
        { id: 'ex-h1', catalogId: 'entretien', duration: 60, assessorId: 'a-ines' },
        { id: 'ex-h2', catalogId: 'presentation', duration: 30, assessorId: 'a-thomas' },
        { id: 'ex-h3', catalogId: 'jeu-role', duration: 30, assessorId: 'a-ines' },
      ],
      competencyIds: ['vision', 'leadership', 'influence', 'agilite'],
      leadAssessorId: 'a-ines',
      secondAssessorIds: ['a-thomas'],
      debriefClientDone: true,
    },
  ]

  const participants: Participant[] = [
    {
      ...blank,
      id: 'pa-jean',
      projectId: 'pr-sanofi',
      firstName: 'Jean',
      lastName: 'Dupont',
      email: 'jean.dupont@exemple.fr',
      currentRole: 'Directeur de site · Le Trait',
      invitedAt: addDays(today, -21),
      welcomeSentAt: addDays(today, -21),
      slot: confirmed(today, '09:00'),
      teamsUrl: teamsLink(),
      hogan: 'done',
      preQuestionnaire: 'done',
      preAnswers: {
        parcours: "Ingénieur de formation, 18 ans dans l'industrie pharmaceutique, dont 6 à la tête d'un site de production de 400 personnes.",
        reussite: 'Le redressement des indicateurs qualité du site en 18 mois, sans plan social.',
        motivation: "Passer d'un site à une vision multi-sites et contribuer à la stratégie industrielle.",
        attentes: 'Un regard extérieur sur mes forces et mes angles morts.',
      },
    },
    {
      ...blank,
      id: 'pa-amelie',
      projectId: 'pr-sanofi',
      firstName: 'Amélie',
      lastName: 'Roux',
      email: 'amelie.roux@exemple.fr',
      currentRole: 'Directrice supply chain Europe',
      invitedAt: addDays(today, -21),
      welcomeSentAt: addDays(today, -21),
      slot: confirmed(today, '13:30'),
      teamsUrl: teamsLink(),
      hogan: 'done',
      preQuestionnaire: 'done',
    },
    {
      ...blank,
      id: 'pa-karim',
      projectId: 'pr-sanofi',
      firstName: 'Karim',
      lastName: 'Haddad',
      email: 'karim.haddad@exemple.fr',
      currentRole: 'Responsable industrialisation',
      invitedAt: addDays(today, -10),
      welcomeSentAt: addDays(today, -10),
      slot: { status: 'proposed', proposals: [{ date: d(6), time: '09:00' }, { date: d(7), time: '09:00' }, { date: d(9), time: '13:30' }], counter: [] },
      hogan: 'done',
      preQuestionnaire: 'todo',
    },
    {
      ...blank,
      id: 'pa-leila',
      projectId: 'pr-orange',
      firstName: 'Leïla',
      lastName: 'Mansouri',
      email: 'leila.mansouri@exemple.fr',
      currentRole: 'Head of B2B Marketing',
      invitedAt: addDays(today, -6),
      welcomeSentAt: addDays(today, -6),
      slot: { status: 'proposed', proposals: [{ date: d(14), time: '08:45' }, { date: d(15), time: '08:45' }, { date: d(21), time: '08:45' }], counter: [] },
      hogan: 'done',
      preQuestionnaire: 'todo',
    },
    {
      ...blank,
      id: 'pa-paul',
      projectId: 'pr-orange',
      firstName: 'Paul',
      lastName: 'Girard',
      email: 'paul.girard@exemple.fr',
      currentRole: 'Directeur des opérations réseau Sud',
      invitedAt: addDays(today, -6),
      welcomeSentAt: addDays(today, -6),
      slot: {
        status: 'counter',
        proposals: [{ date: d(14), time: '08:45' }, { date: d(15), time: '08:45' }],
        counter: [{ date: d(22), time: '08:45' }, { date: d(23), time: '08:45' }],
      },
      hogan: 'todo',
      preQuestionnaire: 'todo',
    },
    {
      ...blank,
      id: 'pa-ines',
      projectId: 'pr-orange',
      firstName: 'Inès',
      lastName: 'Faure',
      email: 'ines.faure@exemple.fr',
      currentRole: 'Responsable transformation digitale',
      invitedAt: addDays(today, -6),
      welcomeSentAt: addDays(today, -6),
      slot: confirmed(d(15), '08:45'),
      hogan: 'done',
      preQuestionnaire: 'done',
    },
    {
      ...blank,
      id: 'pa-hugo',
      projectId: 'pr-orange',
      firstName: 'Hugo',
      lastName: 'Lemaire',
      email: 'hugo.lemaire@exemple.fr',
      currentRole: 'Product Owner senior',
      invitedAt: addDays(today, -1),
      slot: todo(),
      hogan: 'todo',
      preQuestionnaire: 'todo',
    },
    {
      ...blank,
      id: 'pa-clara',
      projectId: 'pr-safran',
      firstName: 'Clara',
      lastName: 'Martin',
      email: 'clara.martin@exemple.fr',
      currentRole: 'Acheteuse famille senior',
      invitedAt: today,
      slot: todo(),
      hogan: 'todo',
      preQuestionnaire: 'todo',
    },
    {
      ...blank,
      id: 'pa-lucas',
      projectId: 'pr-hermes',
      firstName: 'Lucas',
      lastName: 'Petit',
      email: 'lucas.petit@exemple.fr',
      currentRole: 'Directeur régional Retail Ouest',
      invitedAt: addDays(today, -35),
      welcomeSentAt: addDays(today, -35),
      slot: confirmed(addDays(today, -9), '09:00'),
      hogan: 'done',
      preQuestionnaire: 'done',
      dayProgress: 3,
      postQuestionnaire: 'done',
      postAnswers: { organisation: '5', exercices: '4', assesseurs: '5', ressenti: 'Exigeant mais bienveillant.' },
      feedback: {
        status: 'unlocked',
        sessionDate: d(3),
        sessionTime: '10:00',
        summary:
          "Un leader engagé et fédérateur, qui inspire confiance à ses équipes. Votre capacité à porter une vision claire du client final est un atout marquant. L'enjeu des prochains mois : gagner en recul face à la pression opérationnelle pour déléguer davantage.",
        strengths: ['Une vision client incarnée et communicative', "Une écoute réelle, qui crée l'engagement", 'Une grande solidité dans les échanges contradictoires'],
        development: ['Déléguer plus tôt les sujets opérationnels pour libérer du temps stratégique', 'Structurer davantage vos prises de parole devant un comité'],
      },
    },
    {
      ...blank,
      id: 'pa-sarah',
      projectId: 'pr-hermes',
      firstName: 'Sarah',
      lastName: 'Cohen',
      email: 'sarah.cohen@exemple.fr',
      currentRole: 'Directrice de boutique · Paris',
      invitedAt: addDays(today, -35),
      welcomeSentAt: addDays(today, -35),
      slot: confirmed(addDays(today, -8), '09:00'),
      hogan: 'done',
      preQuestionnaire: 'done',
      dayProgress: 3,
      postQuestionnaire: 'done',
      postAnswers: { organisation: '4', exercices: '5', assesseurs: '5', ressenti: 'Très riche.' },
    },
  ]

  return {
    seededOn: today,
    session: null,
    users,
    projects,
    participants,
    assessors,
    notes: {
      'pa-sarah:ex-h1:a-ines': {
        text: "Exemples précis et chiffrés. Situation STAR très claire sur la refonte de l'expérience client en boutique.",
        updatedAt: `${addDays(today, -8)}T10:05:00`,
      },
    },
    grid: {
      'pa-sarah:vision': { score: 4, evidence: 'Projette sa boutique à 3 ans avec des jalons concrets.' },
      'pa-sarah:leadership': { score: 5, evidence: 'Jeu de rôle : a recadré avec tact, collaborateur engagé en sortie.' },
    },
    checklist: { 'a-sophie:pa-jean:dossier': true, 'a-sophie:pa-jean:hogan': true },
  }
}

/** Décale toutes les dates de la démo pour qu'elle reste vivante d'un jour à l'autre. */
export function shiftDemo(state: AppState, days: number): AppState {
  if (!days) return state
  const shift = (o: { date: string; time: string }) => ({ ...o, date: addDays(o.date, days) })
  return {
    ...state,
    seededOn: addDays(state.seededOn, days),
    participants: state.participants.map((p) => ({
      ...p,
      invitedAt: addDays(p.invitedAt, days),
      welcomeSentAt: p.welcomeSentAt && addDays(p.welcomeSentAt, days),
      slot: {
        ...p.slot,
        proposals: p.slot.proposals.map(shift),
        counter: p.slot.counter.map(shift),
        confirmed: p.slot.confirmed && shift(p.slot.confirmed),
      },
      feedback: p.feedback.sessionDate ? { ...p.feedback, sessionDate: addDays(p.feedback.sessionDate, days) } : p.feedback,
    })),
  }
}
